syntax = "proto3";

package chat.v1;

import "type/v1/types.proto";
import "type/v1/enums.proto";

service ChatService {
  rpc Stream(stream ChatStreamRequest) returns (stream ChatStreamResponse);
  rpc CreateChat(CreateChatRequest) returns (CreateChatResponse);
}

message UserProfile {
  int64 id = 1;
  string username = 2;
  string avatar = 3;
}

message ChatMessage {
  int64 id = 1;
  int64 chat_id = 2;
  UserProfile sender = 3;
  string content = 4;
  types.v1.Timestamp created_at = 5;
}

message ChatStreamRequest {
  oneof request {
    SubscriptionRequest subscription = 1;
    MessageSentRequest send_message = 2;
  }
}

message SubscriptionRequest {
  int64 chat_id = 1;
}

message MessageSentRequest {
  int64 client_message_id = 1;
  int64 chat_id = 2;
  int64 sender_id = 3;
  string content = 4;
}

message SubscriptionResponse {
  bool subscribed = 1;
  repeated UserProfile members = 2;
}

message MessageCreatedEvent {
  string client_message_id = 1;
  ChatMessage message = 2;
}

message CreateChatRequest {
  types.v1.ChatType type = 1;
  types.v1.ChatVisibility visibility = 2;
  repeated int64 member_ids = 3;
  string name = 4;
  string description = 5;
}

message CreateChatResponse {
  bool created = 1;
  int64 chat_id = 2;
  repeated ChatMemberResponse members = 3;
  types.v1.ChatType type = 4;
  types.v1.Timestamp created_at = 5;
}

message ChatMemberResponse {
  int64 user_id = 1;
  types.v1.ChatRole role = 2;
}

message ChatStreamResponse {
  oneof response {
    SubscriptionResponse subscription = 1;
    MessageCreatedEvent message_created = 2;
  }
}
